name: Java CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Set up PATH
      run: |
        ls "${ANDROID_HOME}/build-tools/34.0.0"
        echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH
        echo "Updated PATH: $PATH"
    - name: General information
      run: |
        java --version
        d8 --version
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build mod jar
      run: |
        chmod +x gradlew
        ./gradlew deploy
    - name: Upload built jar file
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}
        path: build/libs/${{ github.event.repository.name }}.jar
